web:
  image: 534500277939.dkr.ecr.us-east-1.amazonaws.com/stoutful:latest
  cpu_shares: 100
  mem_limit: 1024000000
  ports:
    - "80:1337"
  links:
    - redis
    - elasticsearch
  environment:
    - NODE_ENV=production
redis:
  image: redis
  cpu_shares: 100
  mem_limit: 1024000000
  ports:
    - "6379:6379"
elasticsearch:
  image: elasticsearch
  cpu_shares: 100
  mem_limit: 1024000000
  ports:
    - "9200:9200"
    - "9300:9300"
