web:
  image: stoutful-dev
  container_name: stoutful-web
  ports:
    - "1337:1337"
  volumes:
    - .:/app
  links:
    - postgres
    - redis
    - elasticsearch
postgres:
  image: postgres
  container_name: stoutful-postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=stoutful
    - POSTGRES_USER=${USER}
redis:
  image: redis
  container_name: stoutful-redis
  ports:
    - "6379:6379"
elasticsearch:
  image: elasticsearch
  container_name: stoutful-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
