web:
  image: alexfu/stoutful
  ports:
    - "1337:1337"
  volumes:
    - .:/app
  links:
    - postgres
    - redis
    - elasticsearch
postgres:
  image: postgres
  ports:
    - "5432:5432"
redis:
  image: redis
  ports:
    - "6379:6379"
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
