#!/usr/bin/env bash

# Clean npm cache
npm cache clean

# Install app dependencies
npm install
bower install --allow-root

# Ensure database is at the latest version
knex migrate:latest

sails lift --silly
