FROM stoutful-base

# Copy ssh keys
ADD ssh/ /root/.ssh/
RUN chmod 600 /root/.ssh/*

# Avoid first connection host confirmation
RUN ssh-keyscan gitlab.com > /root/.ssh/known_hosts

# Clone project
RUN git clone git@gitlab.com:stoutful/stoutful-server.git /app

# Copy ssl cert
ADD ssl/server.crt /app/stoutful.crt
